use_frameworks!

platform :ios, '10.0'

target 'OpenCVX_Example' do
  pod 'OpenCVX', :path => '../'

  target 'OpenCVX_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
